// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/file.proto
// Protobuf Java Version: 4.29.2

package com.halcyon.p2p.file.transfer.proto;

public final class File {
  private File() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      File.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetFilesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetFilesRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string peerName = 1;</code>
     * @return The peerName.
     */
    java.lang.String getPeerName();
    /**
     * <code>string peerName = 1;</code>
     * @return The bytes for peerName.
     */
    com.google.protobuf.ByteString
        getPeerNameBytes();
  }
  /**
   * Protobuf type {@code GetFilesRequest}
   */
  public static final class GetFilesRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GetFilesRequest)
      GetFilesRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        GetFilesRequest.class.getName());
    }
    // Use GetFilesRequest.newBuilder() to construct.
    private GetFilesRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetFilesRequest() {
      peerName_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return File.internal_static_GetFilesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return File.internal_static_GetFilesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              File.GetFilesRequest.class, File.GetFilesRequest.Builder.class);
    }

    public static final int PEERNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object peerName_ = "";
    /**
     * <code>string peerName = 1;</code>
     * @return The peerName.
     */
    @java.lang.Override
    public java.lang.String getPeerName() {
      java.lang.Object ref = peerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peerName_ = s;
        return s;
      }
    }
    /**
     * <code>string peerName = 1;</code>
     * @return The bytes for peerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPeerNameBytes() {
      java.lang.Object ref = peerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(peerName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, peerName_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(peerName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, peerName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof File.GetFilesRequest)) {
        return super.equals(obj);
      }
      File.GetFilesRequest other = (File.GetFilesRequest) obj;

      if (!getPeerName()
          .equals(other.getPeerName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PEERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPeerName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static File.GetFilesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static File.GetFilesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static File.GetFilesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static File.GetFilesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static File.GetFilesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static File.GetFilesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static File.GetFilesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static File.GetFilesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static File.GetFilesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static File.GetFilesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static File.GetFilesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static File.GetFilesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(File.GetFilesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetFilesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetFilesRequest)
        File.GetFilesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return File.internal_static_GetFilesRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return File.internal_static_GetFilesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                File.GetFilesRequest.class, File.GetFilesRequest.Builder.class);
      }

      // Construct using File.GetFilesRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        peerName_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return File.internal_static_GetFilesRequest_descriptor;
      }

      @java.lang.Override
      public File.GetFilesRequest getDefaultInstanceForType() {
        return File.GetFilesRequest.getDefaultInstance();
      }

      @java.lang.Override
      public File.GetFilesRequest build() {
        File.GetFilesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public File.GetFilesRequest buildPartial() {
        File.GetFilesRequest result = new File.GetFilesRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(File.GetFilesRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.peerName_ = peerName_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof File.GetFilesRequest) {
          return mergeFrom((File.GetFilesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(File.GetFilesRequest other) {
        if (other == File.GetFilesRequest.getDefaultInstance()) return this;
        if (!other.getPeerName().isEmpty()) {
          peerName_ = other.peerName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                peerName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object peerName_ = "";
      /**
       * <code>string peerName = 1;</code>
       * @return The peerName.
       */
      public java.lang.String getPeerName() {
        java.lang.Object ref = peerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          peerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string peerName = 1;</code>
       * @return The bytes for peerName.
       */
      public com.google.protobuf.ByteString
          getPeerNameBytes() {
        java.lang.Object ref = peerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          peerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string peerName = 1;</code>
       * @param value The peerName to set.
       * @return This builder for chaining.
       */
      public Builder setPeerName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        peerName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string peerName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeerName() {
        peerName_ = getDefaultInstance().getPeerName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string peerName = 1;</code>
       * @param value The bytes for peerName to set.
       * @return This builder for chaining.
       */
      public Builder setPeerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        peerName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetFilesRequest)
    }

    // @@protoc_insertion_point(class_scope:GetFilesRequest)
    private static final File.GetFilesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new File.GetFilesRequest();
    }

    public static File.GetFilesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetFilesRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetFilesRequest>() {
      @java.lang.Override
      public GetFilesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetFilesRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetFilesRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public File.GetFilesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetFilesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetFilesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string peerName = 1;</code>
     * @return The peerName.
     */
    java.lang.String getPeerName();
    /**
     * <code>string peerName = 1;</code>
     * @return The bytes for peerName.
     */
    com.google.protobuf.ByteString
        getPeerNameBytes();

    /**
     * <code>repeated string fileNames = 2;</code>
     * @return A list containing the fileNames.
     */
    java.util.List<java.lang.String>
        getFileNamesList();
    /**
     * <code>repeated string fileNames = 2;</code>
     * @return The count of fileNames.
     */
    int getFileNamesCount();
    /**
     * <code>repeated string fileNames = 2;</code>
     * @param index The index of the element to return.
     * @return The fileNames at the given index.
     */
    java.lang.String getFileNames(int index);
    /**
     * <code>repeated string fileNames = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the fileNames at the given index.
     */
    com.google.protobuf.ByteString
        getFileNamesBytes(int index);
  }
  /**
   * Protobuf type {@code GetFilesResponse}
   */
  public static final class GetFilesResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GetFilesResponse)
      GetFilesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        GetFilesResponse.class.getName());
    }
    // Use GetFilesResponse.newBuilder() to construct.
    private GetFilesResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetFilesResponse() {
      peerName_ = "";
      fileNames_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return File.internal_static_GetFilesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return File.internal_static_GetFilesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              File.GetFilesResponse.class, File.GetFilesResponse.Builder.class);
    }

    public static final int PEERNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object peerName_ = "";
    /**
     * <code>string peerName = 1;</code>
     * @return The peerName.
     */
    @java.lang.Override
    public java.lang.String getPeerName() {
      java.lang.Object ref = peerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peerName_ = s;
        return s;
      }
    }
    /**
     * <code>string peerName = 1;</code>
     * @return The bytes for peerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPeerNameBytes() {
      java.lang.Object ref = peerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILENAMES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList fileNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string fileNames = 2;</code>
     * @return A list containing the fileNames.
     */
    public com.google.protobuf.ProtocolStringList
        getFileNamesList() {
      return fileNames_;
    }
    /**
     * <code>repeated string fileNames = 2;</code>
     * @return The count of fileNames.
     */
    public int getFileNamesCount() {
      return fileNames_.size();
    }
    /**
     * <code>repeated string fileNames = 2;</code>
     * @param index The index of the element to return.
     * @return The fileNames at the given index.
     */
    public java.lang.String getFileNames(int index) {
      return fileNames_.get(index);
    }
    /**
     * <code>repeated string fileNames = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the fileNames at the given index.
     */
    public com.google.protobuf.ByteString
        getFileNamesBytes(int index) {
      return fileNames_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(peerName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, peerName_);
      }
      for (int i = 0; i < fileNames_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, fileNames_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(peerName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, peerName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fileNames_.size(); i++) {
          dataSize += computeStringSizeNoTag(fileNames_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFileNamesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof File.GetFilesResponse)) {
        return super.equals(obj);
      }
      File.GetFilesResponse other = (File.GetFilesResponse) obj;

      if (!getPeerName()
          .equals(other.getPeerName())) return false;
      if (!getFileNamesList()
          .equals(other.getFileNamesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PEERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPeerName().hashCode();
      if (getFileNamesCount() > 0) {
        hash = (37 * hash) + FILENAMES_FIELD_NUMBER;
        hash = (53 * hash) + getFileNamesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static File.GetFilesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static File.GetFilesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static File.GetFilesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static File.GetFilesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static File.GetFilesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static File.GetFilesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static File.GetFilesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static File.GetFilesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static File.GetFilesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static File.GetFilesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static File.GetFilesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static File.GetFilesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(File.GetFilesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetFilesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetFilesResponse)
        File.GetFilesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return File.internal_static_GetFilesResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return File.internal_static_GetFilesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                File.GetFilesResponse.class, File.GetFilesResponse.Builder.class);
      }

      // Construct using File.GetFilesResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        peerName_ = "";
        fileNames_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return File.internal_static_GetFilesResponse_descriptor;
      }

      @java.lang.Override
      public File.GetFilesResponse getDefaultInstanceForType() {
        return File.GetFilesResponse.getDefaultInstance();
      }

      @java.lang.Override
      public File.GetFilesResponse build() {
        File.GetFilesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public File.GetFilesResponse buildPartial() {
        File.GetFilesResponse result = new File.GetFilesResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(File.GetFilesResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.peerName_ = peerName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          fileNames_.makeImmutable();
          result.fileNames_ = fileNames_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof File.GetFilesResponse) {
          return mergeFrom((File.GetFilesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(File.GetFilesResponse other) {
        if (other == File.GetFilesResponse.getDefaultInstance()) return this;
        if (!other.getPeerName().isEmpty()) {
          peerName_ = other.peerName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.fileNames_.isEmpty()) {
          if (fileNames_.isEmpty()) {
            fileNames_ = other.fileNames_;
            bitField0_ |= 0x00000002;
          } else {
            ensureFileNamesIsMutable();
            fileNames_.addAll(other.fileNames_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                peerName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureFileNamesIsMutable();
                fileNames_.add(s);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object peerName_ = "";
      /**
       * <code>string peerName = 1;</code>
       * @return The peerName.
       */
      public java.lang.String getPeerName() {
        java.lang.Object ref = peerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          peerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string peerName = 1;</code>
       * @return The bytes for peerName.
       */
      public com.google.protobuf.ByteString
          getPeerNameBytes() {
        java.lang.Object ref = peerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          peerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string peerName = 1;</code>
       * @param value The peerName to set.
       * @return This builder for chaining.
       */
      public Builder setPeerName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        peerName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string peerName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeerName() {
        peerName_ = getDefaultInstance().getPeerName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string peerName = 1;</code>
       * @param value The bytes for peerName to set.
       * @return This builder for chaining.
       */
      public Builder setPeerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        peerName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList fileNames_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureFileNamesIsMutable() {
        if (!fileNames_.isModifiable()) {
          fileNames_ = new com.google.protobuf.LazyStringArrayList(fileNames_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated string fileNames = 2;</code>
       * @return A list containing the fileNames.
       */
      public com.google.protobuf.ProtocolStringList
          getFileNamesList() {
        fileNames_.makeImmutable();
        return fileNames_;
      }
      /**
       * <code>repeated string fileNames = 2;</code>
       * @return The count of fileNames.
       */
      public int getFileNamesCount() {
        return fileNames_.size();
      }
      /**
       * <code>repeated string fileNames = 2;</code>
       * @param index The index of the element to return.
       * @return The fileNames at the given index.
       */
      public java.lang.String getFileNames(int index) {
        return fileNames_.get(index);
      }
      /**
       * <code>repeated string fileNames = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the fileNames at the given index.
       */
      public com.google.protobuf.ByteString
          getFileNamesBytes(int index) {
        return fileNames_.getByteString(index);
      }
      /**
       * <code>repeated string fileNames = 2;</code>
       * @param index The index to set the value at.
       * @param value The fileNames to set.
       * @return This builder for chaining.
       */
      public Builder setFileNames(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureFileNamesIsMutable();
        fileNames_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fileNames = 2;</code>
       * @param value The fileNames to add.
       * @return This builder for chaining.
       */
      public Builder addFileNames(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureFileNamesIsMutable();
        fileNames_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fileNames = 2;</code>
       * @param values The fileNames to add.
       * @return This builder for chaining.
       */
      public Builder addAllFileNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureFileNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fileNames_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fileNames = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileNames() {
        fileNames_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fileNames = 2;</code>
       * @param value The bytes of the fileNames to add.
       * @return This builder for chaining.
       */
      public Builder addFileNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureFileNamesIsMutable();
        fileNames_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetFilesResponse)
    }

    // @@protoc_insertion_point(class_scope:GetFilesResponse)
    private static final File.GetFilesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new File.GetFilesResponse();
    }

    public static File.GetFilesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetFilesResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetFilesResponse>() {
      @java.lang.Override
      public GetFilesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetFilesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetFilesResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public File.GetFilesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetFilesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetFilesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetFilesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetFilesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/protobuf/file.proto\"#\n\017GetFil" +
      "esRequest\022\020\n\010peerName\030\001 \001(\t\"7\n\020GetFilesR" +
      "esponse\022\020\n\010peerName\030\001 \001(\t\022\021\n\tfileNames\030\002" +
      " \003(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetFilesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetFilesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetFilesRequest_descriptor,
        new java.lang.String[] { "PeerName", });
    internal_static_GetFilesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetFilesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetFilesResponse_descriptor,
        new java.lang.String[] { "PeerName", "FileNames", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
