package com.halcyon.p2p.file.transfer.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/general.proto
// Protobuf Java Version: 4.29.2

public final class General {
  private General() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      General.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtobufMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtobufMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.HandshakeMessage handshake = 1;</code>
     * @return Whether the handshake field is set.
     */
    boolean hasHandshake();
    /**
     * <code>.HandshakeMessage handshake = 1;</code>
     * @return The handshake.
     */
    Handshake.HandshakeMessage getHandshake();
    /**
     * <code>.HandshakeMessage handshake = 1;</code>
     */
    Handshake.HandshakeMessageOrBuilder getHandshakeOrBuilder();

    /**
     * <code>.PingMessage ping = 2;</code>
     * @return Whether the ping field is set.
     */
    boolean hasPing();
    /**
     * <code>.PingMessage ping = 2;</code>
     * @return The ping.
     */
    Ping.PingMessage getPing();
    /**
     * <code>.PingMessage ping = 2;</code>
     */
    Ping.PingMessageOrBuilder getPingOrBuilder();

    /**
     * <code>.PongMessage pong = 3;</code>
     * @return Whether the pong field is set.
     */
    boolean hasPong();
    /**
     * <code>.PongMessage pong = 3;</code>
     * @return The pong.
     */
    Pong.PongMessage getPong();
    /**
     * <code>.PongMessage pong = 3;</code>
     */
    Pong.PongMessageOrBuilder getPongOrBuilder();

    /**
     * <code>.CancelPingsMessage cancelPings = 4;</code>
     * @return Whether the cancelPings field is set.
     */
    boolean hasCancelPings();
    /**
     * <code>.CancelPingsMessage cancelPings = 4;</code>
     * @return The cancelPings.
     */
    Ping.CancelPingsMessage getCancelPings();
    /**
     * <code>.CancelPingsMessage cancelPings = 4;</code>
     */
    Ping.CancelPingsMessageOrBuilder getCancelPingsOrBuilder();

    /**
     * <code>.CancelPongsMessage cancelPongs = 5;</code>
     * @return Whether the cancelPongs field is set.
     */
    boolean hasCancelPongs();
    /**
     * <code>.CancelPongsMessage cancelPongs = 5;</code>
     * @return The cancelPongs.
     */
    Pong.CancelPongsMessage getCancelPongs();
    /**
     * <code>.CancelPongsMessage cancelPongs = 5;</code>
     */
    Pong.CancelPongsMessageOrBuilder getCancelPongsOrBuilder();

    /**
     * <code>.KeepAliveMessage keepAlive = 6;</code>
     * @return Whether the keepAlive field is set.
     */
    boolean hasKeepAlive();
    /**
     * <code>.KeepAliveMessage keepAlive = 6;</code>
     * @return The keepAlive.
     */
    KeepAlive.KeepAliveMessage getKeepAlive();
    /**
     * <code>.KeepAliveMessage keepAlive = 6;</code>
     */
    KeepAlive.KeepAliveMessageOrBuilder getKeepAliveOrBuilder();

    General.ProtobufMessage.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code ProtobufMessage}
   */
  public static final class ProtobufMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtobufMessage)
      ProtobufMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        ProtobufMessage.class.getName());
    }
    // Use ProtobufMessage.newBuilder() to construct.
    private ProtobufMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProtobufMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return General.internal_static_ProtobufMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return General.internal_static_ProtobufMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              General.ProtobufMessage.class, General.ProtobufMessage.Builder.class);
    }

    private int payloadCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      HANDSHAKE(1),
      PING(2),
      PONG(3),
      CANCELPINGS(4),
      CANCELPONGS(5),
      KEEPALIVE(6),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 1: return HANDSHAKE;
          case 2: return PING;
          case 3: return PONG;
          case 4: return CANCELPINGS;
          case 5: return CANCELPONGS;
          case 6: return KEEPALIVE;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int HANDSHAKE_FIELD_NUMBER = 1;
    /**
     * <code>.HandshakeMessage handshake = 1;</code>
     * @return Whether the handshake field is set.
     */
    @java.lang.Override
    public boolean hasHandshake() {
      return payloadCase_ == 1;
    }
    /**
     * <code>.HandshakeMessage handshake = 1;</code>
     * @return The handshake.
     */
    @java.lang.Override
    public Handshake.HandshakeMessage getHandshake() {
      if (payloadCase_ == 1) {
         return (Handshake.HandshakeMessage) payload_;
      }
      return Handshake.HandshakeMessage.getDefaultInstance();
    }
    /**
     * <code>.HandshakeMessage handshake = 1;</code>
     */
    @java.lang.Override
    public Handshake.HandshakeMessageOrBuilder getHandshakeOrBuilder() {
      if (payloadCase_ == 1) {
         return (Handshake.HandshakeMessage) payload_;
      }
      return Handshake.HandshakeMessage.getDefaultInstance();
    }

    public static final int PING_FIELD_NUMBER = 2;
    /**
     * <code>.PingMessage ping = 2;</code>
     * @return Whether the ping field is set.
     */
    @java.lang.Override
    public boolean hasPing() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.PingMessage ping = 2;</code>
     * @return The ping.
     */
    @java.lang.Override
    public Ping.PingMessage getPing() {
      if (payloadCase_ == 2) {
         return (Ping.PingMessage) payload_;
      }
      return Ping.PingMessage.getDefaultInstance();
    }
    /**
     * <code>.PingMessage ping = 2;</code>
     */
    @java.lang.Override
    public Ping.PingMessageOrBuilder getPingOrBuilder() {
      if (payloadCase_ == 2) {
         return (Ping.PingMessage) payload_;
      }
      return Ping.PingMessage.getDefaultInstance();
    }

    public static final int PONG_FIELD_NUMBER = 3;
    /**
     * <code>.PongMessage pong = 3;</code>
     * @return Whether the pong field is set.
     */
    @java.lang.Override
    public boolean hasPong() {
      return payloadCase_ == 3;
    }
    /**
     * <code>.PongMessage pong = 3;</code>
     * @return The pong.
     */
    @java.lang.Override
    public Pong.PongMessage getPong() {
      if (payloadCase_ == 3) {
         return (Pong.PongMessage) payload_;
      }
      return Pong.PongMessage.getDefaultInstance();
    }
    /**
     * <code>.PongMessage pong = 3;</code>
     */
    @java.lang.Override
    public Pong.PongMessageOrBuilder getPongOrBuilder() {
      if (payloadCase_ == 3) {
         return (Pong.PongMessage) payload_;
      }
      return Pong.PongMessage.getDefaultInstance();
    }

    public static final int CANCELPINGS_FIELD_NUMBER = 4;
    /**
     * <code>.CancelPingsMessage cancelPings = 4;</code>
     * @return Whether the cancelPings field is set.
     */
    @java.lang.Override
    public boolean hasCancelPings() {
      return payloadCase_ == 4;
    }
    /**
     * <code>.CancelPingsMessage cancelPings = 4;</code>
     * @return The cancelPings.
     */
    @java.lang.Override
    public Ping.CancelPingsMessage getCancelPings() {
      if (payloadCase_ == 4) {
         return (Ping.CancelPingsMessage) payload_;
      }
      return Ping.CancelPingsMessage.getDefaultInstance();
    }
    /**
     * <code>.CancelPingsMessage cancelPings = 4;</code>
     */
    @java.lang.Override
    public Ping.CancelPingsMessageOrBuilder getCancelPingsOrBuilder() {
      if (payloadCase_ == 4) {
         return (Ping.CancelPingsMessage) payload_;
      }
      return Ping.CancelPingsMessage.getDefaultInstance();
    }

    public static final int CANCELPONGS_FIELD_NUMBER = 5;
    /**
     * <code>.CancelPongsMessage cancelPongs = 5;</code>
     * @return Whether the cancelPongs field is set.
     */
    @java.lang.Override
    public boolean hasCancelPongs() {
      return payloadCase_ == 5;
    }
    /**
     * <code>.CancelPongsMessage cancelPongs = 5;</code>
     * @return The cancelPongs.
     */
    @java.lang.Override
    public Pong.CancelPongsMessage getCancelPongs() {
      if (payloadCase_ == 5) {
         return (Pong.CancelPongsMessage) payload_;
      }
      return Pong.CancelPongsMessage.getDefaultInstance();
    }
    /**
     * <code>.CancelPongsMessage cancelPongs = 5;</code>
     */
    @java.lang.Override
    public Pong.CancelPongsMessageOrBuilder getCancelPongsOrBuilder() {
      if (payloadCase_ == 5) {
         return (Pong.CancelPongsMessage) payload_;
      }
      return Pong.CancelPongsMessage.getDefaultInstance();
    }

    public static final int KEEPALIVE_FIELD_NUMBER = 6;
    /**
     * <code>.KeepAliveMessage keepAlive = 6;</code>
     * @return Whether the keepAlive field is set.
     */
    @java.lang.Override
    public boolean hasKeepAlive() {
      return payloadCase_ == 6;
    }
    /**
     * <code>.KeepAliveMessage keepAlive = 6;</code>
     * @return The keepAlive.
     */
    @java.lang.Override
    public KeepAlive.KeepAliveMessage getKeepAlive() {
      if (payloadCase_ == 6) {
         return (KeepAlive.KeepAliveMessage) payload_;
      }
      return KeepAlive.KeepAliveMessage.getDefaultInstance();
    }
    /**
     * <code>.KeepAliveMessage keepAlive = 6;</code>
     */
    @java.lang.Override
    public KeepAlive.KeepAliveMessageOrBuilder getKeepAliveOrBuilder() {
      if (payloadCase_ == 6) {
         return (KeepAlive.KeepAliveMessage) payload_;
      }
      return KeepAlive.KeepAliveMessage.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (payloadCase_ == 1) {
        output.writeMessage(1, (Handshake.HandshakeMessage) payload_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (Ping.PingMessage) payload_);
      }
      if (payloadCase_ == 3) {
        output.writeMessage(3, (Pong.PongMessage) payload_);
      }
      if (payloadCase_ == 4) {
        output.writeMessage(4, (Ping.CancelPingsMessage) payload_);
      }
      if (payloadCase_ == 5) {
        output.writeMessage(5, (Pong.CancelPongsMessage) payload_);
      }
      if (payloadCase_ == 6) {
        output.writeMessage(6, (KeepAlive.KeepAliveMessage) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (payloadCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (Handshake.HandshakeMessage) payload_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (Ping.PingMessage) payload_);
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (Pong.PongMessage) payload_);
      }
      if (payloadCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (Ping.CancelPingsMessage) payload_);
      }
      if (payloadCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (Pong.CancelPongsMessage) payload_);
      }
      if (payloadCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (KeepAlive.KeepAliveMessage) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof General.ProtobufMessage)) {
        return super.equals(obj);
      }
      General.ProtobufMessage other = (General.ProtobufMessage) obj;

      if (!getPayloadCase().equals(other.getPayloadCase())) return false;
      switch (payloadCase_) {
        case 1:
          if (!getHandshake()
              .equals(other.getHandshake())) return false;
          break;
        case 2:
          if (!getPing()
              .equals(other.getPing())) return false;
          break;
        case 3:
          if (!getPong()
              .equals(other.getPong())) return false;
          break;
        case 4:
          if (!getCancelPings()
              .equals(other.getCancelPings())) return false;
          break;
        case 5:
          if (!getCancelPongs()
              .equals(other.getCancelPongs())) return false;
          break;
        case 6:
          if (!getKeepAlive()
              .equals(other.getKeepAlive())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (payloadCase_) {
        case 1:
          hash = (37 * hash) + HANDSHAKE_FIELD_NUMBER;
          hash = (53 * hash) + getHandshake().hashCode();
          break;
        case 2:
          hash = (37 * hash) + PING_FIELD_NUMBER;
          hash = (53 * hash) + getPing().hashCode();
          break;
        case 3:
          hash = (37 * hash) + PONG_FIELD_NUMBER;
          hash = (53 * hash) + getPong().hashCode();
          break;
        case 4:
          hash = (37 * hash) + CANCELPINGS_FIELD_NUMBER;
          hash = (53 * hash) + getCancelPings().hashCode();
          break;
        case 5:
          hash = (37 * hash) + CANCELPONGS_FIELD_NUMBER;
          hash = (53 * hash) + getCancelPongs().hashCode();
          break;
        case 6:
          hash = (37 * hash) + KEEPALIVE_FIELD_NUMBER;
          hash = (53 * hash) + getKeepAlive().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static General.ProtobufMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static General.ProtobufMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static General.ProtobufMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static General.ProtobufMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static General.ProtobufMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static General.ProtobufMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static General.ProtobufMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static General.ProtobufMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static General.ProtobufMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static General.ProtobufMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static General.ProtobufMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static General.ProtobufMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(General.ProtobufMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtobufMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtobufMessage)
        General.ProtobufMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return General.internal_static_ProtobufMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return General.internal_static_ProtobufMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                General.ProtobufMessage.class, General.ProtobufMessage.Builder.class);
      }

      // Construct using General.ProtobufMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (handshakeBuilder_ != null) {
          handshakeBuilder_.clear();
        }
        if (pingBuilder_ != null) {
          pingBuilder_.clear();
        }
        if (pongBuilder_ != null) {
          pongBuilder_.clear();
        }
        if (cancelPingsBuilder_ != null) {
          cancelPingsBuilder_.clear();
        }
        if (cancelPongsBuilder_ != null) {
          cancelPongsBuilder_.clear();
        }
        if (keepAliveBuilder_ != null) {
          keepAliveBuilder_.clear();
        }
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return General.internal_static_ProtobufMessage_descriptor;
      }

      @java.lang.Override
      public General.ProtobufMessage getDefaultInstanceForType() {
        return General.ProtobufMessage.getDefaultInstance();
      }

      @java.lang.Override
      public General.ProtobufMessage build() {
        General.ProtobufMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public General.ProtobufMessage buildPartial() {
        General.ProtobufMessage result = new General.ProtobufMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(General.ProtobufMessage result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(General.ProtobufMessage result) {
        result.payloadCase_ = payloadCase_;
        result.payload_ = this.payload_;
        if (payloadCase_ == 1 &&
            handshakeBuilder_ != null) {
          result.payload_ = handshakeBuilder_.build();
        }
        if (payloadCase_ == 2 &&
            pingBuilder_ != null) {
          result.payload_ = pingBuilder_.build();
        }
        if (payloadCase_ == 3 &&
            pongBuilder_ != null) {
          result.payload_ = pongBuilder_.build();
        }
        if (payloadCase_ == 4 &&
            cancelPingsBuilder_ != null) {
          result.payload_ = cancelPingsBuilder_.build();
        }
        if (payloadCase_ == 5 &&
            cancelPongsBuilder_ != null) {
          result.payload_ = cancelPongsBuilder_.build();
        }
        if (payloadCase_ == 6 &&
            keepAliveBuilder_ != null) {
          result.payload_ = keepAliveBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof General.ProtobufMessage) {
          return mergeFrom((General.ProtobufMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(General.ProtobufMessage other) {
        if (other == General.ProtobufMessage.getDefaultInstance()) return this;
        switch (other.getPayloadCase()) {
          case HANDSHAKE: {
            mergeHandshake(other.getHandshake());
            break;
          }
          case PING: {
            mergePing(other.getPing());
            break;
          }
          case PONG: {
            mergePong(other.getPong());
            break;
          }
          case CANCELPINGS: {
            mergeCancelPings(other.getCancelPings());
            break;
          }
          case CANCELPONGS: {
            mergeCancelPongs(other.getCancelPongs());
            break;
          }
          case KEEPALIVE: {
            mergeKeepAlive(other.getKeepAlive());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getHandshakeFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 1;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getPingFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 2;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getPongFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 3;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getCancelPingsFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 4;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getCancelPongsFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 5;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getKeepAliveFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 6;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          Handshake.HandshakeMessage, Handshake.HandshakeMessage.Builder, Handshake.HandshakeMessageOrBuilder> handshakeBuilder_;
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       * @return Whether the handshake field is set.
       */
      @java.lang.Override
      public boolean hasHandshake() {
        return payloadCase_ == 1;
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       * @return The handshake.
       */
      @java.lang.Override
      public Handshake.HandshakeMessage getHandshake() {
        if (handshakeBuilder_ == null) {
          if (payloadCase_ == 1) {
            return (Handshake.HandshakeMessage) payload_;
          }
          return Handshake.HandshakeMessage.getDefaultInstance();
        } else {
          if (payloadCase_ == 1) {
            return handshakeBuilder_.getMessage();
          }
          return Handshake.HandshakeMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       */
      public Builder setHandshake(Handshake.HandshakeMessage value) {
        if (handshakeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          handshakeBuilder_.setMessage(value);
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       */
      public Builder setHandshake(
          Handshake.HandshakeMessage.Builder builderForValue) {
        if (handshakeBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          handshakeBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       */
      public Builder mergeHandshake(Handshake.HandshakeMessage value) {
        if (handshakeBuilder_ == null) {
          if (payloadCase_ == 1 &&
              payload_ != Handshake.HandshakeMessage.getDefaultInstance()) {
            payload_ = Handshake.HandshakeMessage.newBuilder((Handshake.HandshakeMessage) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 1) {
            handshakeBuilder_.mergeFrom(value);
          } else {
            handshakeBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       */
      public Builder clearHandshake() {
        if (handshakeBuilder_ == null) {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
          }
          handshakeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       */
      public Handshake.HandshakeMessage.Builder getHandshakeBuilder() {
        return getHandshakeFieldBuilder().getBuilder();
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       */
      @java.lang.Override
      public Handshake.HandshakeMessageOrBuilder getHandshakeOrBuilder() {
        if ((payloadCase_ == 1) && (handshakeBuilder_ != null)) {
          return handshakeBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 1) {
            return (Handshake.HandshakeMessage) payload_;
          }
          return Handshake.HandshakeMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Handshake.HandshakeMessage, Handshake.HandshakeMessage.Builder, Handshake.HandshakeMessageOrBuilder> 
          getHandshakeFieldBuilder() {
        if (handshakeBuilder_ == null) {
          if (!(payloadCase_ == 1)) {
            payload_ = Handshake.HandshakeMessage.getDefaultInstance();
          }
          handshakeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Handshake.HandshakeMessage, Handshake.HandshakeMessage.Builder, Handshake.HandshakeMessageOrBuilder>(
                  (Handshake.HandshakeMessage) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 1;
        onChanged();
        return handshakeBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          Ping.PingMessage, Ping.PingMessage.Builder, Ping.PingMessageOrBuilder> pingBuilder_;
      /**
       * <code>.PingMessage ping = 2;</code>
       * @return Whether the ping field is set.
       */
      @java.lang.Override
      public boolean hasPing() {
        return payloadCase_ == 2;
      }
      /**
       * <code>.PingMessage ping = 2;</code>
       * @return The ping.
       */
      @java.lang.Override
      public Ping.PingMessage getPing() {
        if (pingBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (Ping.PingMessage) payload_;
          }
          return Ping.PingMessage.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return pingBuilder_.getMessage();
          }
          return Ping.PingMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.PingMessage ping = 2;</code>
       */
      public Builder setPing(Ping.PingMessage value) {
        if (pingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          pingBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.PingMessage ping = 2;</code>
       */
      public Builder setPing(
          Ping.PingMessage.Builder builderForValue) {
        if (pingBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          pingBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.PingMessage ping = 2;</code>
       */
      public Builder mergePing(Ping.PingMessage value) {
        if (pingBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != Ping.PingMessage.getDefaultInstance()) {
            payload_ = Ping.PingMessage.newBuilder((Ping.PingMessage) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            pingBuilder_.mergeFrom(value);
          } else {
            pingBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.PingMessage ping = 2;</code>
       */
      public Builder clearPing() {
        if (pingBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          pingBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.PingMessage ping = 2;</code>
       */
      public Ping.PingMessage.Builder getPingBuilder() {
        return getPingFieldBuilder().getBuilder();
      }
      /**
       * <code>.PingMessage ping = 2;</code>
       */
      @java.lang.Override
      public Ping.PingMessageOrBuilder getPingOrBuilder() {
        if ((payloadCase_ == 2) && (pingBuilder_ != null)) {
          return pingBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (Ping.PingMessage) payload_;
          }
          return Ping.PingMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.PingMessage ping = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Ping.PingMessage, Ping.PingMessage.Builder, Ping.PingMessageOrBuilder> 
          getPingFieldBuilder() {
        if (pingBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = Ping.PingMessage.getDefaultInstance();
          }
          pingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Ping.PingMessage, Ping.PingMessage.Builder, Ping.PingMessageOrBuilder>(
                  (Ping.PingMessage) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        onChanged();
        return pingBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          Pong.PongMessage, Pong.PongMessage.Builder, Pong.PongMessageOrBuilder> pongBuilder_;
      /**
       * <code>.PongMessage pong = 3;</code>
       * @return Whether the pong field is set.
       */
      @java.lang.Override
      public boolean hasPong() {
        return payloadCase_ == 3;
      }
      /**
       * <code>.PongMessage pong = 3;</code>
       * @return The pong.
       */
      @java.lang.Override
      public Pong.PongMessage getPong() {
        if (pongBuilder_ == null) {
          if (payloadCase_ == 3) {
            return (Pong.PongMessage) payload_;
          }
          return Pong.PongMessage.getDefaultInstance();
        } else {
          if (payloadCase_ == 3) {
            return pongBuilder_.getMessage();
          }
          return Pong.PongMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.PongMessage pong = 3;</code>
       */
      public Builder setPong(Pong.PongMessage value) {
        if (pongBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          pongBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>.PongMessage pong = 3;</code>
       */
      public Builder setPong(
          Pong.PongMessage.Builder builderForValue) {
        if (pongBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          pongBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>.PongMessage pong = 3;</code>
       */
      public Builder mergePong(Pong.PongMessage value) {
        if (pongBuilder_ == null) {
          if (payloadCase_ == 3 &&
              payload_ != Pong.PongMessage.getDefaultInstance()) {
            payload_ = Pong.PongMessage.newBuilder((Pong.PongMessage) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 3) {
            pongBuilder_.mergeFrom(value);
          } else {
            pongBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>.PongMessage pong = 3;</code>
       */
      public Builder clearPong() {
        if (pongBuilder_ == null) {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
          }
          pongBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.PongMessage pong = 3;</code>
       */
      public Pong.PongMessage.Builder getPongBuilder() {
        return getPongFieldBuilder().getBuilder();
      }
      /**
       * <code>.PongMessage pong = 3;</code>
       */
      @java.lang.Override
      public Pong.PongMessageOrBuilder getPongOrBuilder() {
        if ((payloadCase_ == 3) && (pongBuilder_ != null)) {
          return pongBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 3) {
            return (Pong.PongMessage) payload_;
          }
          return Pong.PongMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.PongMessage pong = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Pong.PongMessage, Pong.PongMessage.Builder, Pong.PongMessageOrBuilder> 
          getPongFieldBuilder() {
        if (pongBuilder_ == null) {
          if (!(payloadCase_ == 3)) {
            payload_ = Pong.PongMessage.getDefaultInstance();
          }
          pongBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Pong.PongMessage, Pong.PongMessage.Builder, Pong.PongMessageOrBuilder>(
                  (Pong.PongMessage) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 3;
        onChanged();
        return pongBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          Ping.CancelPingsMessage, Ping.CancelPingsMessage.Builder, Ping.CancelPingsMessageOrBuilder> cancelPingsBuilder_;
      /**
       * <code>.CancelPingsMessage cancelPings = 4;</code>
       * @return Whether the cancelPings field is set.
       */
      @java.lang.Override
      public boolean hasCancelPings() {
        return payloadCase_ == 4;
      }
      /**
       * <code>.CancelPingsMessage cancelPings = 4;</code>
       * @return The cancelPings.
       */
      @java.lang.Override
      public Ping.CancelPingsMessage getCancelPings() {
        if (cancelPingsBuilder_ == null) {
          if (payloadCase_ == 4) {
            return (Ping.CancelPingsMessage) payload_;
          }
          return Ping.CancelPingsMessage.getDefaultInstance();
        } else {
          if (payloadCase_ == 4) {
            return cancelPingsBuilder_.getMessage();
          }
          return Ping.CancelPingsMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.CancelPingsMessage cancelPings = 4;</code>
       */
      public Builder setCancelPings(Ping.CancelPingsMessage value) {
        if (cancelPingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          cancelPingsBuilder_.setMessage(value);
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>.CancelPingsMessage cancelPings = 4;</code>
       */
      public Builder setCancelPings(
          Ping.CancelPingsMessage.Builder builderForValue) {
        if (cancelPingsBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          cancelPingsBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>.CancelPingsMessage cancelPings = 4;</code>
       */
      public Builder mergeCancelPings(Ping.CancelPingsMessage value) {
        if (cancelPingsBuilder_ == null) {
          if (payloadCase_ == 4 &&
              payload_ != Ping.CancelPingsMessage.getDefaultInstance()) {
            payload_ = Ping.CancelPingsMessage.newBuilder((Ping.CancelPingsMessage) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 4) {
            cancelPingsBuilder_.mergeFrom(value);
          } else {
            cancelPingsBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>.CancelPingsMessage cancelPings = 4;</code>
       */
      public Builder clearCancelPings() {
        if (cancelPingsBuilder_ == null) {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
          }
          cancelPingsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.CancelPingsMessage cancelPings = 4;</code>
       */
      public Ping.CancelPingsMessage.Builder getCancelPingsBuilder() {
        return getCancelPingsFieldBuilder().getBuilder();
      }
      /**
       * <code>.CancelPingsMessage cancelPings = 4;</code>
       */
      @java.lang.Override
      public Ping.CancelPingsMessageOrBuilder getCancelPingsOrBuilder() {
        if ((payloadCase_ == 4) && (cancelPingsBuilder_ != null)) {
          return cancelPingsBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 4) {
            return (Ping.CancelPingsMessage) payload_;
          }
          return Ping.CancelPingsMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.CancelPingsMessage cancelPings = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Ping.CancelPingsMessage, Ping.CancelPingsMessage.Builder, Ping.CancelPingsMessageOrBuilder> 
          getCancelPingsFieldBuilder() {
        if (cancelPingsBuilder_ == null) {
          if (!(payloadCase_ == 4)) {
            payload_ = Ping.CancelPingsMessage.getDefaultInstance();
          }
          cancelPingsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Ping.CancelPingsMessage, Ping.CancelPingsMessage.Builder, Ping.CancelPingsMessageOrBuilder>(
                  (Ping.CancelPingsMessage) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 4;
        onChanged();
        return cancelPingsBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          Pong.CancelPongsMessage, Pong.CancelPongsMessage.Builder, Pong.CancelPongsMessageOrBuilder> cancelPongsBuilder_;
      /**
       * <code>.CancelPongsMessage cancelPongs = 5;</code>
       * @return Whether the cancelPongs field is set.
       */
      @java.lang.Override
      public boolean hasCancelPongs() {
        return payloadCase_ == 5;
      }
      /**
       * <code>.CancelPongsMessage cancelPongs = 5;</code>
       * @return The cancelPongs.
       */
      @java.lang.Override
      public Pong.CancelPongsMessage getCancelPongs() {
        if (cancelPongsBuilder_ == null) {
          if (payloadCase_ == 5) {
            return (Pong.CancelPongsMessage) payload_;
          }
          return Pong.CancelPongsMessage.getDefaultInstance();
        } else {
          if (payloadCase_ == 5) {
            return cancelPongsBuilder_.getMessage();
          }
          return Pong.CancelPongsMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.CancelPongsMessage cancelPongs = 5;</code>
       */
      public Builder setCancelPongs(Pong.CancelPongsMessage value) {
        if (cancelPongsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          cancelPongsBuilder_.setMessage(value);
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>.CancelPongsMessage cancelPongs = 5;</code>
       */
      public Builder setCancelPongs(
          Pong.CancelPongsMessage.Builder builderForValue) {
        if (cancelPongsBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          cancelPongsBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>.CancelPongsMessage cancelPongs = 5;</code>
       */
      public Builder mergeCancelPongs(Pong.CancelPongsMessage value) {
        if (cancelPongsBuilder_ == null) {
          if (payloadCase_ == 5 &&
              payload_ != Pong.CancelPongsMessage.getDefaultInstance()) {
            payload_ = Pong.CancelPongsMessage.newBuilder((Pong.CancelPongsMessage) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 5) {
            cancelPongsBuilder_.mergeFrom(value);
          } else {
            cancelPongsBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>.CancelPongsMessage cancelPongs = 5;</code>
       */
      public Builder clearCancelPongs() {
        if (cancelPongsBuilder_ == null) {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
          }
          cancelPongsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.CancelPongsMessage cancelPongs = 5;</code>
       */
      public Pong.CancelPongsMessage.Builder getCancelPongsBuilder() {
        return getCancelPongsFieldBuilder().getBuilder();
      }
      /**
       * <code>.CancelPongsMessage cancelPongs = 5;</code>
       */
      @java.lang.Override
      public Pong.CancelPongsMessageOrBuilder getCancelPongsOrBuilder() {
        if ((payloadCase_ == 5) && (cancelPongsBuilder_ != null)) {
          return cancelPongsBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 5) {
            return (Pong.CancelPongsMessage) payload_;
          }
          return Pong.CancelPongsMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.CancelPongsMessage cancelPongs = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Pong.CancelPongsMessage, Pong.CancelPongsMessage.Builder, Pong.CancelPongsMessageOrBuilder> 
          getCancelPongsFieldBuilder() {
        if (cancelPongsBuilder_ == null) {
          if (!(payloadCase_ == 5)) {
            payload_ = Pong.CancelPongsMessage.getDefaultInstance();
          }
          cancelPongsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Pong.CancelPongsMessage, Pong.CancelPongsMessage.Builder, Pong.CancelPongsMessageOrBuilder>(
                  (Pong.CancelPongsMessage) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 5;
        onChanged();
        return cancelPongsBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          KeepAlive.KeepAliveMessage, KeepAlive.KeepAliveMessage.Builder, KeepAlive.KeepAliveMessageOrBuilder> keepAliveBuilder_;
      /**
       * <code>.KeepAliveMessage keepAlive = 6;</code>
       * @return Whether the keepAlive field is set.
       */
      @java.lang.Override
      public boolean hasKeepAlive() {
        return payloadCase_ == 6;
      }
      /**
       * <code>.KeepAliveMessage keepAlive = 6;</code>
       * @return The keepAlive.
       */
      @java.lang.Override
      public KeepAlive.KeepAliveMessage getKeepAlive() {
        if (keepAliveBuilder_ == null) {
          if (payloadCase_ == 6) {
            return (KeepAlive.KeepAliveMessage) payload_;
          }
          return KeepAlive.KeepAliveMessage.getDefaultInstance();
        } else {
          if (payloadCase_ == 6) {
            return keepAliveBuilder_.getMessage();
          }
          return KeepAlive.KeepAliveMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.KeepAliveMessage keepAlive = 6;</code>
       */
      public Builder setKeepAlive(KeepAlive.KeepAliveMessage value) {
        if (keepAliveBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          keepAliveBuilder_.setMessage(value);
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>.KeepAliveMessage keepAlive = 6;</code>
       */
      public Builder setKeepAlive(
          KeepAlive.KeepAliveMessage.Builder builderForValue) {
        if (keepAliveBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          keepAliveBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>.KeepAliveMessage keepAlive = 6;</code>
       */
      public Builder mergeKeepAlive(KeepAlive.KeepAliveMessage value) {
        if (keepAliveBuilder_ == null) {
          if (payloadCase_ == 6 &&
              payload_ != KeepAlive.KeepAliveMessage.getDefaultInstance()) {
            payload_ = KeepAlive.KeepAliveMessage.newBuilder((KeepAlive.KeepAliveMessage) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 6) {
            keepAliveBuilder_.mergeFrom(value);
          } else {
            keepAliveBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>.KeepAliveMessage keepAlive = 6;</code>
       */
      public Builder clearKeepAlive() {
        if (keepAliveBuilder_ == null) {
          if (payloadCase_ == 6) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 6) {
            payloadCase_ = 0;
            payload_ = null;
          }
          keepAliveBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.KeepAliveMessage keepAlive = 6;</code>
       */
      public KeepAlive.KeepAliveMessage.Builder getKeepAliveBuilder() {
        return getKeepAliveFieldBuilder().getBuilder();
      }
      /**
       * <code>.KeepAliveMessage keepAlive = 6;</code>
       */
      @java.lang.Override
      public KeepAlive.KeepAliveMessageOrBuilder getKeepAliveOrBuilder() {
        if ((payloadCase_ == 6) && (keepAliveBuilder_ != null)) {
          return keepAliveBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 6) {
            return (KeepAlive.KeepAliveMessage) payload_;
          }
          return KeepAlive.KeepAliveMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.KeepAliveMessage keepAlive = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          KeepAlive.KeepAliveMessage, KeepAlive.KeepAliveMessage.Builder, KeepAlive.KeepAliveMessageOrBuilder> 
          getKeepAliveFieldBuilder() {
        if (keepAliveBuilder_ == null) {
          if (!(payloadCase_ == 6)) {
            payload_ = KeepAlive.KeepAliveMessage.getDefaultInstance();
          }
          keepAliveBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              KeepAlive.KeepAliveMessage, KeepAlive.KeepAliveMessage.Builder, KeepAlive.KeepAliveMessageOrBuilder>(
                  (KeepAlive.KeepAliveMessage) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 6;
        onChanged();
        return keepAliveBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ProtobufMessage)
    }

    // @@protoc_insertion_point(class_scope:ProtobufMessage)
    private static final General.ProtobufMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new General.ProtobufMessage();
    }

    public static General.ProtobufMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtobufMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProtobufMessage>() {
      @java.lang.Override
      public ProtobufMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProtobufMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtobufMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public General.ProtobufMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtobufMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtobufMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/protobuf/general.proto\032!src/m" +
      "ain/protobuf/handshake.proto\032\034src/main/p" +
      "rotobuf/ping.proto\032\034src/main/protobuf/po" +
      "ng.proto\032\"src/main/protobuf/keep_alive.p" +
      "roto\"\200\002\n\017ProtobufMessage\022&\n\thandshake\030\001 " +
      "\001(\0132\021.HandshakeMessageH\000\022\034\n\004ping\030\002 \001(\0132\014" +
      ".PingMessageH\000\022\034\n\004pong\030\003 \001(\0132\014.PongMessa" +
      "geH\000\022*\n\013cancelPings\030\004 \001(\0132\023.CancelPingsM" +
      "essageH\000\022*\n\013cancelPongs\030\005 \001(\0132\023.CancelPo" +
      "ngsMessageH\000\022&\n\tkeepAlive\030\006 \001(\0132\021.KeepAl" +
      "iveMessageH\000B\t\n\007payloadb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Handshake.getDescriptor(),
          Ping.getDescriptor(),
          Pong.getDescriptor(),
          KeepAlive.getDescriptor(),
        });
    internal_static_ProtobufMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtobufMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtobufMessage_descriptor,
        new java.lang.String[] { "Handshake", "Ping", "Pong", "CancelPings", "CancelPongs", "KeepAlive", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
    Handshake.getDescriptor();
    Ping.getDescriptor();
    Pong.getDescriptor();
    KeepAlive.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
