package com.halcyon.p2p.file.transfer.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/general.proto
// Protobuf Java Version: 4.29.2

public final class General {
  private General() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      General.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtobufMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtobufMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.HandshakeMessage handshake = 1;</code>
     * @return Whether the handshake field is set.
     */
    boolean hasHandshake();
    /**
     * <code>.HandshakeMessage handshake = 1;</code>
     * @return The handshake.
     */
    Handshake.HandshakeMessage getHandshake();
    /**
     * <code>.HandshakeMessage handshake = 1;</code>
     */
    Handshake.HandshakeMessageOrBuilder getHandshakeOrBuilder();

    General.ProtobufMessage.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code ProtobufMessage}
   */
  public static final class ProtobufMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtobufMessage)
      ProtobufMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        ProtobufMessage.class.getName());
    }
    // Use ProtobufMessage.newBuilder() to construct.
    private ProtobufMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProtobufMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return General.internal_static_ProtobufMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return General.internal_static_ProtobufMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              General.ProtobufMessage.class, General.ProtobufMessage.Builder.class);
    }

    private int payloadCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      HANDSHAKE(1),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 1: return HANDSHAKE;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int HANDSHAKE_FIELD_NUMBER = 1;
    /**
     * <code>.HandshakeMessage handshake = 1;</code>
     * @return Whether the handshake field is set.
     */
    @java.lang.Override
    public boolean hasHandshake() {
      return payloadCase_ == 1;
    }
    /**
     * <code>.HandshakeMessage handshake = 1;</code>
     * @return The handshake.
     */
    @java.lang.Override
    public Handshake.HandshakeMessage getHandshake() {
      if (payloadCase_ == 1) {
         return (Handshake.HandshakeMessage) payload_;
      }
      return Handshake.HandshakeMessage.getDefaultInstance();
    }
    /**
     * <code>.HandshakeMessage handshake = 1;</code>
     */
    @java.lang.Override
    public Handshake.HandshakeMessageOrBuilder getHandshakeOrBuilder() {
      if (payloadCase_ == 1) {
         return (Handshake.HandshakeMessage) payload_;
      }
      return Handshake.HandshakeMessage.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (payloadCase_ == 1) {
        output.writeMessage(1, (Handshake.HandshakeMessage) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (payloadCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (Handshake.HandshakeMessage) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof General.ProtobufMessage)) {
        return super.equals(obj);
      }
      General.ProtobufMessage other = (General.ProtobufMessage) obj;

      if (!getPayloadCase().equals(other.getPayloadCase())) return false;
      switch (payloadCase_) {
        case 1:
          if (!getHandshake()
              .equals(other.getHandshake())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (payloadCase_) {
        case 1:
          hash = (37 * hash) + HANDSHAKE_FIELD_NUMBER;
          hash = (53 * hash) + getHandshake().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static General.ProtobufMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static General.ProtobufMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static General.ProtobufMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static General.ProtobufMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static General.ProtobufMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static General.ProtobufMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static General.ProtobufMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static General.ProtobufMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static General.ProtobufMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static General.ProtobufMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static General.ProtobufMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static General.ProtobufMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(General.ProtobufMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtobufMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtobufMessage)
        General.ProtobufMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return General.internal_static_ProtobufMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return General.internal_static_ProtobufMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                General.ProtobufMessage.class, General.ProtobufMessage.Builder.class);
      }

      // Construct using General.ProtobufMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (handshakeBuilder_ != null) {
          handshakeBuilder_.clear();
        }
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return General.internal_static_ProtobufMessage_descriptor;
      }

      @java.lang.Override
      public General.ProtobufMessage getDefaultInstanceForType() {
        return General.ProtobufMessage.getDefaultInstance();
      }

      @java.lang.Override
      public General.ProtobufMessage build() {
        General.ProtobufMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public General.ProtobufMessage buildPartial() {
        General.ProtobufMessage result = new General.ProtobufMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(General.ProtobufMessage result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(General.ProtobufMessage result) {
        result.payloadCase_ = payloadCase_;
        result.payload_ = this.payload_;
        if (payloadCase_ == 1 &&
            handshakeBuilder_ != null) {
          result.payload_ = handshakeBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof General.ProtobufMessage) {
          return mergeFrom((General.ProtobufMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(General.ProtobufMessage other) {
        if (other == General.ProtobufMessage.getDefaultInstance()) return this;
        switch (other.getPayloadCase()) {
          case HANDSHAKE: {
            mergeHandshake(other.getHandshake());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getHandshakeFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 1;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          Handshake.HandshakeMessage, Handshake.HandshakeMessage.Builder, Handshake.HandshakeMessageOrBuilder> handshakeBuilder_;
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       * @return Whether the handshake field is set.
       */
      @java.lang.Override
      public boolean hasHandshake() {
        return payloadCase_ == 1;
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       * @return The handshake.
       */
      @java.lang.Override
      public Handshake.HandshakeMessage getHandshake() {
        if (handshakeBuilder_ == null) {
          if (payloadCase_ == 1) {
            return (Handshake.HandshakeMessage) payload_;
          }
          return Handshake.HandshakeMessage.getDefaultInstance();
        } else {
          if (payloadCase_ == 1) {
            return handshakeBuilder_.getMessage();
          }
          return Handshake.HandshakeMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       */
      public Builder setHandshake(Handshake.HandshakeMessage value) {
        if (handshakeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          handshakeBuilder_.setMessage(value);
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       */
      public Builder setHandshake(
          Handshake.HandshakeMessage.Builder builderForValue) {
        if (handshakeBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          handshakeBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       */
      public Builder mergeHandshake(Handshake.HandshakeMessage value) {
        if (handshakeBuilder_ == null) {
          if (payloadCase_ == 1 &&
              payload_ != Handshake.HandshakeMessage.getDefaultInstance()) {
            payload_ = Handshake.HandshakeMessage.newBuilder((Handshake.HandshakeMessage) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 1) {
            handshakeBuilder_.mergeFrom(value);
          } else {
            handshakeBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       */
      public Builder clearHandshake() {
        if (handshakeBuilder_ == null) {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
          }
          handshakeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       */
      public Handshake.HandshakeMessage.Builder getHandshakeBuilder() {
        return getHandshakeFieldBuilder().getBuilder();
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       */
      @java.lang.Override
      public Handshake.HandshakeMessageOrBuilder getHandshakeOrBuilder() {
        if ((payloadCase_ == 1) && (handshakeBuilder_ != null)) {
          return handshakeBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 1) {
            return (Handshake.HandshakeMessage) payload_;
          }
          return Handshake.HandshakeMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.HandshakeMessage handshake = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Handshake.HandshakeMessage, Handshake.HandshakeMessage.Builder, Handshake.HandshakeMessageOrBuilder> 
          getHandshakeFieldBuilder() {
        if (handshakeBuilder_ == null) {
          if (!(payloadCase_ == 1)) {
            payload_ = Handshake.HandshakeMessage.getDefaultInstance();
          }
          handshakeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Handshake.HandshakeMessage, Handshake.HandshakeMessage.Builder, Handshake.HandshakeMessageOrBuilder>(
                  (Handshake.HandshakeMessage) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 1;
        onChanged();
        return handshakeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ProtobufMessage)
    }

    // @@protoc_insertion_point(class_scope:ProtobufMessage)
    private static final General.ProtobufMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new General.ProtobufMessage();
    }

    public static General.ProtobufMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtobufMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProtobufMessage>() {
      @java.lang.Override
      public ProtobufMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProtobufMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtobufMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public General.ProtobufMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtobufMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtobufMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/protobuf/general.proto\032!src/m" +
      "ain/protobuf/handshake.proto\"D\n\017Protobuf" +
      "Message\022&\n\thandshake\030\001 \001(\0132\021.HandshakeMe" +
      "ssageH\000B\t\n\007payloadb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Handshake.getDescriptor(),
        });
    internal_static_ProtobufMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtobufMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtobufMessage_descriptor,
        new java.lang.String[] { "Handshake", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
    Handshake.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
