package com.halcyon.p2p.file.transfer.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/ping.proto
// Protobuf Java Version: 4.29.2

public final class Ping {
  private Ping() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      Ping.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PingMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PingMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string peerName = 1;</code>
     * @return The peerName.
     */
    java.lang.String getPeerName();
    /**
     * <code>string peerName = 1;</code>
     * @return The bytes for peerName.
     */
    com.google.protobuf.ByteString
        getPeerNameBytes();

    /**
     * <code>int32 ttl = 2;</code>
     * @return The ttl.
     */
    int getTtl();

    /**
     * <code>int32 hops = 3;</code>
     * @return The hops.
     */
    int getHops();

    /**
     * <code>int64 pingTimeoutDurationInMillis = 4;</code>
     * @return The pingTimeoutDurationInMillis.
     */
    long getPingTimeoutDurationInMillis();

    /**
     * <code>int64 pingStartTimestamp = 5;</code>
     * @return The pingStartTimestamp.
     */
    long getPingStartTimestamp();
  }
  /**
   * Protobuf type {@code PingMessage}
   */
  public static final class PingMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PingMessage)
      PingMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        PingMessage.class.getName());
    }
    // Use PingMessage.newBuilder() to construct.
    private PingMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PingMessage() {
      peerName_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Ping.internal_static_PingMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Ping.internal_static_PingMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Ping.PingMessage.class, Ping.PingMessage.Builder.class);
    }

    public static final int PEERNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object peerName_ = "";
    /**
     * <code>string peerName = 1;</code>
     * @return The peerName.
     */
    @java.lang.Override
    public java.lang.String getPeerName() {
      java.lang.Object ref = peerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peerName_ = s;
        return s;
      }
    }
    /**
     * <code>string peerName = 1;</code>
     * @return The bytes for peerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPeerNameBytes() {
      java.lang.Object ref = peerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TTL_FIELD_NUMBER = 2;
    private int ttl_ = 0;
    /**
     * <code>int32 ttl = 2;</code>
     * @return The ttl.
     */
    @java.lang.Override
    public int getTtl() {
      return ttl_;
    }

    public static final int HOPS_FIELD_NUMBER = 3;
    private int hops_ = 0;
    /**
     * <code>int32 hops = 3;</code>
     * @return The hops.
     */
    @java.lang.Override
    public int getHops() {
      return hops_;
    }

    public static final int PINGTIMEOUTDURATIONINMILLIS_FIELD_NUMBER = 4;
    private long pingTimeoutDurationInMillis_ = 0L;
    /**
     * <code>int64 pingTimeoutDurationInMillis = 4;</code>
     * @return The pingTimeoutDurationInMillis.
     */
    @java.lang.Override
    public long getPingTimeoutDurationInMillis() {
      return pingTimeoutDurationInMillis_;
    }

    public static final int PINGSTARTTIMESTAMP_FIELD_NUMBER = 5;
    private long pingStartTimestamp_ = 0L;
    /**
     * <code>int64 pingStartTimestamp = 5;</code>
     * @return The pingStartTimestamp.
     */
    @java.lang.Override
    public long getPingStartTimestamp() {
      return pingStartTimestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(peerName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, peerName_);
      }
      if (ttl_ != 0) {
        output.writeInt32(2, ttl_);
      }
      if (hops_ != 0) {
        output.writeInt32(3, hops_);
      }
      if (pingTimeoutDurationInMillis_ != 0L) {
        output.writeInt64(4, pingTimeoutDurationInMillis_);
      }
      if (pingStartTimestamp_ != 0L) {
        output.writeInt64(5, pingStartTimestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(peerName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, peerName_);
      }
      if (ttl_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ttl_);
      }
      if (hops_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, hops_);
      }
      if (pingTimeoutDurationInMillis_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, pingTimeoutDurationInMillis_);
      }
      if (pingStartTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, pingStartTimestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Ping.PingMessage)) {
        return super.equals(obj);
      }
      Ping.PingMessage other = (Ping.PingMessage) obj;

      if (!getPeerName()
          .equals(other.getPeerName())) return false;
      if (getTtl()
          != other.getTtl()) return false;
      if (getHops()
          != other.getHops()) return false;
      if (getPingTimeoutDurationInMillis()
          != other.getPingTimeoutDurationInMillis()) return false;
      if (getPingStartTimestamp()
          != other.getPingStartTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PEERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPeerName().hashCode();
      hash = (37 * hash) + TTL_FIELD_NUMBER;
      hash = (53 * hash) + getTtl();
      hash = (37 * hash) + HOPS_FIELD_NUMBER;
      hash = (53 * hash) + getHops();
      hash = (37 * hash) + PINGTIMEOUTDURATIONINMILLIS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPingTimeoutDurationInMillis());
      hash = (37 * hash) + PINGSTARTTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPingStartTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Ping.PingMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ping.PingMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ping.PingMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ping.PingMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ping.PingMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ping.PingMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ping.PingMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Ping.PingMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Ping.PingMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Ping.PingMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Ping.PingMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Ping.PingMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Ping.PingMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PingMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PingMessage)
        Ping.PingMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Ping.internal_static_PingMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Ping.internal_static_PingMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Ping.PingMessage.class, Ping.PingMessage.Builder.class);
      }

      // Construct using Ping.PingMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        peerName_ = "";
        ttl_ = 0;
        hops_ = 0;
        pingTimeoutDurationInMillis_ = 0L;
        pingStartTimestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Ping.internal_static_PingMessage_descriptor;
      }

      @java.lang.Override
      public Ping.PingMessage getDefaultInstanceForType() {
        return Ping.PingMessage.getDefaultInstance();
      }

      @java.lang.Override
      public Ping.PingMessage build() {
        Ping.PingMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Ping.PingMessage buildPartial() {
        Ping.PingMessage result = new Ping.PingMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Ping.PingMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.peerName_ = peerName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.ttl_ = ttl_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.hops_ = hops_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.pingTimeoutDurationInMillis_ = pingTimeoutDurationInMillis_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.pingStartTimestamp_ = pingStartTimestamp_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Ping.PingMessage) {
          return mergeFrom((Ping.PingMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Ping.PingMessage other) {
        if (other == Ping.PingMessage.getDefaultInstance()) return this;
        if (!other.getPeerName().isEmpty()) {
          peerName_ = other.peerName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getTtl() != 0) {
          setTtl(other.getTtl());
        }
        if (other.getHops() != 0) {
          setHops(other.getHops());
        }
        if (other.getPingTimeoutDurationInMillis() != 0L) {
          setPingTimeoutDurationInMillis(other.getPingTimeoutDurationInMillis());
        }
        if (other.getPingStartTimestamp() != 0L) {
          setPingStartTimestamp(other.getPingStartTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                peerName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                ttl_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                hops_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                pingTimeoutDurationInMillis_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                pingStartTimestamp_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object peerName_ = "";
      /**
       * <code>string peerName = 1;</code>
       * @return The peerName.
       */
      public java.lang.String getPeerName() {
        java.lang.Object ref = peerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          peerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string peerName = 1;</code>
       * @return The bytes for peerName.
       */
      public com.google.protobuf.ByteString
          getPeerNameBytes() {
        java.lang.Object ref = peerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          peerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string peerName = 1;</code>
       * @param value The peerName to set.
       * @return This builder for chaining.
       */
      public Builder setPeerName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        peerName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string peerName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeerName() {
        peerName_ = getDefaultInstance().getPeerName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string peerName = 1;</code>
       * @param value The bytes for peerName to set.
       * @return This builder for chaining.
       */
      public Builder setPeerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        peerName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int ttl_ ;
      /**
       * <code>int32 ttl = 2;</code>
       * @return The ttl.
       */
      @java.lang.Override
      public int getTtl() {
        return ttl_;
      }
      /**
       * <code>int32 ttl = 2;</code>
       * @param value The ttl to set.
       * @return This builder for chaining.
       */
      public Builder setTtl(int value) {

        ttl_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ttl = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTtl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ttl_ = 0;
        onChanged();
        return this;
      }

      private int hops_ ;
      /**
       * <code>int32 hops = 3;</code>
       * @return The hops.
       */
      @java.lang.Override
      public int getHops() {
        return hops_;
      }
      /**
       * <code>int32 hops = 3;</code>
       * @param value The hops to set.
       * @return This builder for chaining.
       */
      public Builder setHops(int value) {

        hops_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hops = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHops() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hops_ = 0;
        onChanged();
        return this;
      }

      private long pingTimeoutDurationInMillis_ ;
      /**
       * <code>int64 pingTimeoutDurationInMillis = 4;</code>
       * @return The pingTimeoutDurationInMillis.
       */
      @java.lang.Override
      public long getPingTimeoutDurationInMillis() {
        return pingTimeoutDurationInMillis_;
      }
      /**
       * <code>int64 pingTimeoutDurationInMillis = 4;</code>
       * @param value The pingTimeoutDurationInMillis to set.
       * @return This builder for chaining.
       */
      public Builder setPingTimeoutDurationInMillis(long value) {

        pingTimeoutDurationInMillis_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 pingTimeoutDurationInMillis = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPingTimeoutDurationInMillis() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pingTimeoutDurationInMillis_ = 0L;
        onChanged();
        return this;
      }

      private long pingStartTimestamp_ ;
      /**
       * <code>int64 pingStartTimestamp = 5;</code>
       * @return The pingStartTimestamp.
       */
      @java.lang.Override
      public long getPingStartTimestamp() {
        return pingStartTimestamp_;
      }
      /**
       * <code>int64 pingStartTimestamp = 5;</code>
       * @param value The pingStartTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setPingStartTimestamp(long value) {

        pingStartTimestamp_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 pingStartTimestamp = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPingStartTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        pingStartTimestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PingMessage)
    }

    // @@protoc_insertion_point(class_scope:PingMessage)
    private static final Ping.PingMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Ping.PingMessage();
    }

    public static Ping.PingMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PingMessage>
        PARSER = new com.google.protobuf.AbstractParser<PingMessage>() {
      @java.lang.Override
      public PingMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PingMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PingMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Ping.PingMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CancelPingsMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CancelPingsMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string peerName = 1;</code>
     * @return The peerName.
     */
    java.lang.String getPeerName();
    /**
     * <code>string peerName = 1;</code>
     * @return The bytes for peerName.
     */
    com.google.protobuf.ByteString
        getPeerNameBytes();
  }
  /**
   * Protobuf type {@code CancelPingsMessage}
   */
  public static final class CancelPingsMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CancelPingsMessage)
      CancelPingsMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        CancelPingsMessage.class.getName());
    }
    // Use CancelPingsMessage.newBuilder() to construct.
    private CancelPingsMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CancelPingsMessage() {
      peerName_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Ping.internal_static_CancelPingsMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Ping.internal_static_CancelPingsMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Ping.CancelPingsMessage.class, Ping.CancelPingsMessage.Builder.class);
    }

    public static final int PEERNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object peerName_ = "";
    /**
     * <code>string peerName = 1;</code>
     * @return The peerName.
     */
    @java.lang.Override
    public java.lang.String getPeerName() {
      java.lang.Object ref = peerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peerName_ = s;
        return s;
      }
    }
    /**
     * <code>string peerName = 1;</code>
     * @return The bytes for peerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPeerNameBytes() {
      java.lang.Object ref = peerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(peerName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, peerName_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(peerName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, peerName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Ping.CancelPingsMessage)) {
        return super.equals(obj);
      }
      Ping.CancelPingsMessage other = (Ping.CancelPingsMessage) obj;

      if (!getPeerName()
          .equals(other.getPeerName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PEERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPeerName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Ping.CancelPingsMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ping.CancelPingsMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ping.CancelPingsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ping.CancelPingsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ping.CancelPingsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ping.CancelPingsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ping.CancelPingsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Ping.CancelPingsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Ping.CancelPingsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Ping.CancelPingsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Ping.CancelPingsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Ping.CancelPingsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Ping.CancelPingsMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CancelPingsMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CancelPingsMessage)
        Ping.CancelPingsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Ping.internal_static_CancelPingsMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Ping.internal_static_CancelPingsMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Ping.CancelPingsMessage.class, Ping.CancelPingsMessage.Builder.class);
      }

      // Construct using Ping.CancelPingsMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        peerName_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Ping.internal_static_CancelPingsMessage_descriptor;
      }

      @java.lang.Override
      public Ping.CancelPingsMessage getDefaultInstanceForType() {
        return Ping.CancelPingsMessage.getDefaultInstance();
      }

      @java.lang.Override
      public Ping.CancelPingsMessage build() {
        Ping.CancelPingsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Ping.CancelPingsMessage buildPartial() {
        Ping.CancelPingsMessage result = new Ping.CancelPingsMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Ping.CancelPingsMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.peerName_ = peerName_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Ping.CancelPingsMessage) {
          return mergeFrom((Ping.CancelPingsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Ping.CancelPingsMessage other) {
        if (other == Ping.CancelPingsMessage.getDefaultInstance()) return this;
        if (!other.getPeerName().isEmpty()) {
          peerName_ = other.peerName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                peerName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object peerName_ = "";
      /**
       * <code>string peerName = 1;</code>
       * @return The peerName.
       */
      public java.lang.String getPeerName() {
        java.lang.Object ref = peerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          peerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string peerName = 1;</code>
       * @return The bytes for peerName.
       */
      public com.google.protobuf.ByteString
          getPeerNameBytes() {
        java.lang.Object ref = peerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          peerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string peerName = 1;</code>
       * @param value The peerName to set.
       * @return This builder for chaining.
       */
      public Builder setPeerName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        peerName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string peerName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeerName() {
        peerName_ = getDefaultInstance().getPeerName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string peerName = 1;</code>
       * @param value The bytes for peerName to set.
       * @return This builder for chaining.
       */
      public Builder setPeerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        peerName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CancelPingsMessage)
    }

    // @@protoc_insertion_point(class_scope:CancelPingsMessage)
    private static final Ping.CancelPingsMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Ping.CancelPingsMessage();
    }

    public static Ping.CancelPingsMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CancelPingsMessage>
        PARSER = new com.google.protobuf.AbstractParser<CancelPingsMessage>() {
      @java.lang.Override
      public CancelPingsMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CancelPingsMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CancelPingsMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Ping.CancelPingsMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PingMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PingMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CancelPingsMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CancelPingsMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/protobuf/ping.proto\"{\n\013PingMe" +
      "ssage\022\020\n\010peerName\030\001 \001(\t\022\013\n\003ttl\030\002 \001(\005\022\014\n\004" +
      "hops\030\003 \001(\005\022#\n\033pingTimeoutDurationInMilli" +
      "s\030\004 \001(\003\022\032\n\022pingStartTimestamp\030\005 \001(\003\"&\n\022C" +
      "ancelPingsMessage\022\020\n\010peerName\030\001 \001(\tb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PingMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PingMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PingMessage_descriptor,
        new java.lang.String[] { "PeerName", "Ttl", "Hops", "PingTimeoutDurationInMillis", "PingStartTimestamp", });
    internal_static_CancelPingsMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CancelPingsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CancelPingsMessage_descriptor,
        new java.lang.String[] { "PeerName", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
