// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/pong.proto
// Protobuf Java Version: 4.29.2

package com.halcyon.p2p.file.transfer.proto;

public final class Pong {
  private Pong() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      Pong.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PongMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PongMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string pingPeerName = 1;</code>
     * @return The pingPeerName.
     */
    java.lang.String getPingPeerName();
    /**
     * <code>string pingPeerName = 1;</code>
     * @return The bytes for pingPeerName.
     */
    com.google.protobuf.ByteString
        getPingPeerNameBytes();

    /**
     * <code>string senderPeerName = 2;</code>
     * @return The senderPeerName.
     */
    java.lang.String getSenderPeerName();
    /**
     * <code>string senderPeerName = 2;</code>
     * @return The bytes for senderPeerName.
     */
    com.google.protobuf.ByteString
        getSenderPeerNameBytes();

    /**
     * <code>string peerName = 3;</code>
     * @return The peerName.
     */
    java.lang.String getPeerName();
    /**
     * <code>string peerName = 3;</code>
     * @return The bytes for peerName.
     */
    com.google.protobuf.ByteString
        getPeerNameBytes();

    /**
     * <code>string serverHost = 4;</code>
     * @return The serverHost.
     */
    java.lang.String getServerHost();
    /**
     * <code>string serverHost = 4;</code>
     * @return The bytes for serverHost.
     */
    com.google.protobuf.ByteString
        getServerHostBytes();

    /**
     * <code>int32 serverPort = 5;</code>
     * @return The serverPort.
     */
    int getServerPort();

    /**
     * <code>int32 ttl = 6;</code>
     * @return The ttl.
     */
    int getTtl();

    /**
     * <code>int32 hops = 7;</code>
     * @return The hops.
     */
    int getHops();
  }
  /**
   * Protobuf type {@code PongMessage}
   */
  public static final class PongMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PongMessage)
      PongMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        PongMessage.class.getName());
    }
    // Use PongMessage.newBuilder() to construct.
    private PongMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PongMessage() {
      pingPeerName_ = "";
      senderPeerName_ = "";
      peerName_ = "";
      serverHost_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Pong.internal_static_PongMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Pong.internal_static_PongMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Pong.PongMessage.class, Pong.PongMessage.Builder.class);
    }

    public static final int PINGPEERNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object pingPeerName_ = "";
    /**
     * <code>string pingPeerName = 1;</code>
     * @return The pingPeerName.
     */
    @java.lang.Override
    public java.lang.String getPingPeerName() {
      java.lang.Object ref = pingPeerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pingPeerName_ = s;
        return s;
      }
    }
    /**
     * <code>string pingPeerName = 1;</code>
     * @return The bytes for pingPeerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPingPeerNameBytes() {
      java.lang.Object ref = pingPeerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pingPeerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERPEERNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object senderPeerName_ = "";
    /**
     * <code>string senderPeerName = 2;</code>
     * @return The senderPeerName.
     */
    @java.lang.Override
    public java.lang.String getSenderPeerName() {
      java.lang.Object ref = senderPeerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderPeerName_ = s;
        return s;
      }
    }
    /**
     * <code>string senderPeerName = 2;</code>
     * @return The bytes for senderPeerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderPeerNameBytes() {
      java.lang.Object ref = senderPeerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderPeerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PEERNAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object peerName_ = "";
    /**
     * <code>string peerName = 3;</code>
     * @return The peerName.
     */
    @java.lang.Override
    public java.lang.String getPeerName() {
      java.lang.Object ref = peerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peerName_ = s;
        return s;
      }
    }
    /**
     * <code>string peerName = 3;</code>
     * @return The bytes for peerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPeerNameBytes() {
      java.lang.Object ref = peerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERHOST_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object serverHost_ = "";
    /**
     * <code>string serverHost = 4;</code>
     * @return The serverHost.
     */
    @java.lang.Override
    public java.lang.String getServerHost() {
      java.lang.Object ref = serverHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverHost_ = s;
        return s;
      }
    }
    /**
     * <code>string serverHost = 4;</code>
     * @return The bytes for serverHost.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServerHostBytes() {
      java.lang.Object ref = serverHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERPORT_FIELD_NUMBER = 5;
    private int serverPort_ = 0;
    /**
     * <code>int32 serverPort = 5;</code>
     * @return The serverPort.
     */
    @java.lang.Override
    public int getServerPort() {
      return serverPort_;
    }

    public static final int TTL_FIELD_NUMBER = 6;
    private int ttl_ = 0;
    /**
     * <code>int32 ttl = 6;</code>
     * @return The ttl.
     */
    @java.lang.Override
    public int getTtl() {
      return ttl_;
    }

    public static final int HOPS_FIELD_NUMBER = 7;
    private int hops_ = 0;
    /**
     * <code>int32 hops = 7;</code>
     * @return The hops.
     */
    @java.lang.Override
    public int getHops() {
      return hops_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pingPeerName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, pingPeerName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderPeerName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, senderPeerName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(peerName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, peerName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverHost_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, serverHost_);
      }
      if (serverPort_ != 0) {
        output.writeInt32(5, serverPort_);
      }
      if (ttl_ != 0) {
        output.writeInt32(6, ttl_);
      }
      if (hops_ != 0) {
        output.writeInt32(7, hops_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pingPeerName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, pingPeerName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderPeerName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, senderPeerName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(peerName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, peerName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverHost_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, serverHost_);
      }
      if (serverPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, serverPort_);
      }
      if (ttl_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, ttl_);
      }
      if (hops_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, hops_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Pong.PongMessage)) {
        return super.equals(obj);
      }
      Pong.PongMessage other = (Pong.PongMessage) obj;

      if (!getPingPeerName()
          .equals(other.getPingPeerName())) return false;
      if (!getSenderPeerName()
          .equals(other.getSenderPeerName())) return false;
      if (!getPeerName()
          .equals(other.getPeerName())) return false;
      if (!getServerHost()
          .equals(other.getServerHost())) return false;
      if (getServerPort()
          != other.getServerPort()) return false;
      if (getTtl()
          != other.getTtl()) return false;
      if (getHops()
          != other.getHops()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PINGPEERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPingPeerName().hashCode();
      hash = (37 * hash) + SENDERPEERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSenderPeerName().hashCode();
      hash = (37 * hash) + PEERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPeerName().hashCode();
      hash = (37 * hash) + SERVERHOST_FIELD_NUMBER;
      hash = (53 * hash) + getServerHost().hashCode();
      hash = (37 * hash) + SERVERPORT_FIELD_NUMBER;
      hash = (53 * hash) + getServerPort();
      hash = (37 * hash) + TTL_FIELD_NUMBER;
      hash = (53 * hash) + getTtl();
      hash = (37 * hash) + HOPS_FIELD_NUMBER;
      hash = (53 * hash) + getHops();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Pong.PongMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pong.PongMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pong.PongMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pong.PongMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pong.PongMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pong.PongMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pong.PongMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Pong.PongMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Pong.PongMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Pong.PongMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Pong.PongMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Pong.PongMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Pong.PongMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PongMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PongMessage)
        Pong.PongMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Pong.internal_static_PongMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Pong.internal_static_PongMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Pong.PongMessage.class, Pong.PongMessage.Builder.class);
      }

      // Construct using Pong.PongMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        pingPeerName_ = "";
        senderPeerName_ = "";
        peerName_ = "";
        serverHost_ = "";
        serverPort_ = 0;
        ttl_ = 0;
        hops_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Pong.internal_static_PongMessage_descriptor;
      }

      @java.lang.Override
      public Pong.PongMessage getDefaultInstanceForType() {
        return Pong.PongMessage.getDefaultInstance();
      }

      @java.lang.Override
      public Pong.PongMessage build() {
        Pong.PongMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Pong.PongMessage buildPartial() {
        Pong.PongMessage result = new Pong.PongMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Pong.PongMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.pingPeerName_ = pingPeerName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.senderPeerName_ = senderPeerName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.peerName_ = peerName_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.serverHost_ = serverHost_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.serverPort_ = serverPort_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.ttl_ = ttl_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.hops_ = hops_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Pong.PongMessage) {
          return mergeFrom((Pong.PongMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Pong.PongMessage other) {
        if (other == Pong.PongMessage.getDefaultInstance()) return this;
        if (!other.getPingPeerName().isEmpty()) {
          pingPeerName_ = other.pingPeerName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getSenderPeerName().isEmpty()) {
          senderPeerName_ = other.senderPeerName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getPeerName().isEmpty()) {
          peerName_ = other.peerName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getServerHost().isEmpty()) {
          serverHost_ = other.serverHost_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getServerPort() != 0) {
          setServerPort(other.getServerPort());
        }
        if (other.getTtl() != 0) {
          setTtl(other.getTtl());
        }
        if (other.getHops() != 0) {
          setHops(other.getHops());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                pingPeerName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                senderPeerName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                peerName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                serverHost_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                serverPort_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                ttl_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                hops_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object pingPeerName_ = "";
      /**
       * <code>string pingPeerName = 1;</code>
       * @return The pingPeerName.
       */
      public java.lang.String getPingPeerName() {
        java.lang.Object ref = pingPeerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pingPeerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pingPeerName = 1;</code>
       * @return The bytes for pingPeerName.
       */
      public com.google.protobuf.ByteString
          getPingPeerNameBytes() {
        java.lang.Object ref = pingPeerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pingPeerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pingPeerName = 1;</code>
       * @param value The pingPeerName to set.
       * @return This builder for chaining.
       */
      public Builder setPingPeerName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        pingPeerName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string pingPeerName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPingPeerName() {
        pingPeerName_ = getDefaultInstance().getPingPeerName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string pingPeerName = 1;</code>
       * @param value The bytes for pingPeerName to set.
       * @return This builder for chaining.
       */
      public Builder setPingPeerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        pingPeerName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object senderPeerName_ = "";
      /**
       * <code>string senderPeerName = 2;</code>
       * @return The senderPeerName.
       */
      public java.lang.String getSenderPeerName() {
        java.lang.Object ref = senderPeerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderPeerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderPeerName = 2;</code>
       * @return The bytes for senderPeerName.
       */
      public com.google.protobuf.ByteString
          getSenderPeerNameBytes() {
        java.lang.Object ref = senderPeerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderPeerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderPeerName = 2;</code>
       * @param value The senderPeerName to set.
       * @return This builder for chaining.
       */
      public Builder setSenderPeerName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        senderPeerName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string senderPeerName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderPeerName() {
        senderPeerName_ = getDefaultInstance().getSenderPeerName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string senderPeerName = 2;</code>
       * @param value The bytes for senderPeerName to set.
       * @return This builder for chaining.
       */
      public Builder setSenderPeerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        senderPeerName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object peerName_ = "";
      /**
       * <code>string peerName = 3;</code>
       * @return The peerName.
       */
      public java.lang.String getPeerName() {
        java.lang.Object ref = peerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          peerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string peerName = 3;</code>
       * @return The bytes for peerName.
       */
      public com.google.protobuf.ByteString
          getPeerNameBytes() {
        java.lang.Object ref = peerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          peerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string peerName = 3;</code>
       * @param value The peerName to set.
       * @return This builder for chaining.
       */
      public Builder setPeerName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        peerName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string peerName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeerName() {
        peerName_ = getDefaultInstance().getPeerName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string peerName = 3;</code>
       * @param value The bytes for peerName to set.
       * @return This builder for chaining.
       */
      public Builder setPeerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        peerName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object serverHost_ = "";
      /**
       * <code>string serverHost = 4;</code>
       * @return The serverHost.
       */
      public java.lang.String getServerHost() {
        java.lang.Object ref = serverHost_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverHost_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serverHost = 4;</code>
       * @return The bytes for serverHost.
       */
      public com.google.protobuf.ByteString
          getServerHostBytes() {
        java.lang.Object ref = serverHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serverHost = 4;</code>
       * @param value The serverHost to set.
       * @return This builder for chaining.
       */
      public Builder setServerHost(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        serverHost_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string serverHost = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerHost() {
        serverHost_ = getDefaultInstance().getServerHost();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string serverHost = 4;</code>
       * @param value The bytes for serverHost to set.
       * @return This builder for chaining.
       */
      public Builder setServerHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serverHost_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int serverPort_ ;
      /**
       * <code>int32 serverPort = 5;</code>
       * @return The serverPort.
       */
      @java.lang.Override
      public int getServerPort() {
        return serverPort_;
      }
      /**
       * <code>int32 serverPort = 5;</code>
       * @param value The serverPort to set.
       * @return This builder for chaining.
       */
      public Builder setServerPort(int value) {

        serverPort_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serverPort = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerPort() {
        bitField0_ = (bitField0_ & ~0x00000010);
        serverPort_ = 0;
        onChanged();
        return this;
      }

      private int ttl_ ;
      /**
       * <code>int32 ttl = 6;</code>
       * @return The ttl.
       */
      @java.lang.Override
      public int getTtl() {
        return ttl_;
      }
      /**
       * <code>int32 ttl = 6;</code>
       * @param value The ttl to set.
       * @return This builder for chaining.
       */
      public Builder setTtl(int value) {

        ttl_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ttl = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTtl() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ttl_ = 0;
        onChanged();
        return this;
      }

      private int hops_ ;
      /**
       * <code>int32 hops = 7;</code>
       * @return The hops.
       */
      @java.lang.Override
      public int getHops() {
        return hops_;
      }
      /**
       * <code>int32 hops = 7;</code>
       * @param value The hops to set.
       * @return This builder for chaining.
       */
      public Builder setHops(int value) {

        hops_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hops = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearHops() {
        bitField0_ = (bitField0_ & ~0x00000040);
        hops_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PongMessage)
    }

    // @@protoc_insertion_point(class_scope:PongMessage)
    private static final Pong.PongMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Pong.PongMessage();
    }

    public static Pong.PongMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PongMessage>
        PARSER = new com.google.protobuf.AbstractParser<PongMessage>() {
      @java.lang.Override
      public PongMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PongMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PongMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Pong.PongMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CancelPongsMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CancelPongsMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string peerName = 1;</code>
     * @return The peerName.
     */
    java.lang.String getPeerName();
    /**
     * <code>string peerName = 1;</code>
     * @return The bytes for peerName.
     */
    com.google.protobuf.ByteString
        getPeerNameBytes();
  }
  /**
   * Protobuf type {@code CancelPongsMessage}
   */
  public static final class CancelPongsMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CancelPongsMessage)
      CancelPongsMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        CancelPongsMessage.class.getName());
    }
    // Use CancelPongsMessage.newBuilder() to construct.
    private CancelPongsMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CancelPongsMessage() {
      peerName_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Pong.internal_static_CancelPongsMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Pong.internal_static_CancelPongsMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Pong.CancelPongsMessage.class, Pong.CancelPongsMessage.Builder.class);
    }

    public static final int PEERNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object peerName_ = "";
    /**
     * <code>string peerName = 1;</code>
     * @return The peerName.
     */
    @java.lang.Override
    public java.lang.String getPeerName() {
      java.lang.Object ref = peerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peerName_ = s;
        return s;
      }
    }
    /**
     * <code>string peerName = 1;</code>
     * @return The bytes for peerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPeerNameBytes() {
      java.lang.Object ref = peerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(peerName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, peerName_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(peerName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, peerName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Pong.CancelPongsMessage)) {
        return super.equals(obj);
      }
      Pong.CancelPongsMessage other = (Pong.CancelPongsMessage) obj;

      if (!getPeerName()
          .equals(other.getPeerName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PEERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPeerName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Pong.CancelPongsMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pong.CancelPongsMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pong.CancelPongsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pong.CancelPongsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pong.CancelPongsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pong.CancelPongsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pong.CancelPongsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Pong.CancelPongsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Pong.CancelPongsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Pong.CancelPongsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Pong.CancelPongsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Pong.CancelPongsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Pong.CancelPongsMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CancelPongsMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CancelPongsMessage)
        Pong.CancelPongsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Pong.internal_static_CancelPongsMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Pong.internal_static_CancelPongsMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Pong.CancelPongsMessage.class, Pong.CancelPongsMessage.Builder.class);
      }

      // Construct using Pong.CancelPongsMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        peerName_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Pong.internal_static_CancelPongsMessage_descriptor;
      }

      @java.lang.Override
      public Pong.CancelPongsMessage getDefaultInstanceForType() {
        return Pong.CancelPongsMessage.getDefaultInstance();
      }

      @java.lang.Override
      public Pong.CancelPongsMessage build() {
        Pong.CancelPongsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Pong.CancelPongsMessage buildPartial() {
        Pong.CancelPongsMessage result = new Pong.CancelPongsMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Pong.CancelPongsMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.peerName_ = peerName_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Pong.CancelPongsMessage) {
          return mergeFrom((Pong.CancelPongsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Pong.CancelPongsMessage other) {
        if (other == Pong.CancelPongsMessage.getDefaultInstance()) return this;
        if (!other.getPeerName().isEmpty()) {
          peerName_ = other.peerName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                peerName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object peerName_ = "";
      /**
       * <code>string peerName = 1;</code>
       * @return The peerName.
       */
      public java.lang.String getPeerName() {
        java.lang.Object ref = peerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          peerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string peerName = 1;</code>
       * @return The bytes for peerName.
       */
      public com.google.protobuf.ByteString
          getPeerNameBytes() {
        java.lang.Object ref = peerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          peerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string peerName = 1;</code>
       * @param value The peerName to set.
       * @return This builder for chaining.
       */
      public Builder setPeerName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        peerName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string peerName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeerName() {
        peerName_ = getDefaultInstance().getPeerName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string peerName = 1;</code>
       * @param value The bytes for peerName to set.
       * @return This builder for chaining.
       */
      public Builder setPeerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        peerName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CancelPongsMessage)
    }

    // @@protoc_insertion_point(class_scope:CancelPongsMessage)
    private static final Pong.CancelPongsMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Pong.CancelPongsMessage();
    }

    public static Pong.CancelPongsMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CancelPongsMessage>
        PARSER = new com.google.protobuf.AbstractParser<CancelPongsMessage>() {
      @java.lang.Override
      public CancelPongsMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CancelPongsMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CancelPongsMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Pong.CancelPongsMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PongMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PongMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CancelPongsMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CancelPongsMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/protobuf/pong.proto\"\220\001\n\013PongM" +
      "essage\022\024\n\014pingPeerName\030\001 \001(\t\022\026\n\016senderPe" +
      "erName\030\002 \001(\t\022\020\n\010peerName\030\003 \001(\t\022\022\n\nserver" +
      "Host\030\004 \001(\t\022\022\n\nserverPort\030\005 \001(\005\022\013\n\003ttl\030\006 " +
      "\001(\005\022\014\n\004hops\030\007 \001(\005\"&\n\022CancelPongsMessage\022" +
      "\020\n\010peerName\030\001 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PongMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PongMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PongMessage_descriptor,
        new java.lang.String[] { "PingPeerName", "SenderPeerName", "PeerName", "ServerHost", "ServerPort", "Ttl", "Hops", });
    internal_static_CancelPongsMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CancelPongsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CancelPongsMessage_descriptor,
        new java.lang.String[] { "PeerName", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
